export const IPC = {
  DIALOG_OPEN_FOLDER: 'dialog:openFolder',
  FS_READ_DIR: 'fs:readDir',
  FS_READ_FILE: 'fs:readFile',
  FS_WRITE_FILE: 'fs:writeFile',
  FS_CREATE_FILE: 'fs:createFile',
  FS_CREATE_DIR: 'fs:createDir',
  FS_DELETE_PATH: 'fs:deletePath',
  FS_RENAME_PATH: 'fs:renamePath',
  FS_MOVE_PATH: 'fs:movePath',
  FS_PATH_EXISTS: 'fs:pathExists',
  WORKSPACE_GET: 'workspace:get',
  WORKSPACE_SET: 'workspace:set',
  WORKSPACE_CHANGED: 'workspace:changed',
  RUN_CODE: 'run-code',
  TERMINAL_OUT: 'terminal-out',
  SYS_STATS: 'sys-stats',
  GIT_STATUS: 'git:status',
  GIT_ADD: 'git:add',
  GIT_UNSTAGE: 'git:unstage',
  GIT_DISCARD: 'git:discard',
  GIT_COMMIT: 'git:commit',
  GIT_PUSH: 'git:push',
  GIT_PULL: 'git:pull',
} as const
